import Mathlib

/-!
# Verifier Invariance under Transformations

Let `X` be a task space, `A` an answer space, and `V : X → A → Bool` a verifier.
Let `T_X : X → X` and `T_A : A → A` be transformations.

We formalize and prove:
1. If `V` is invariant under `(T_X, T_A)`, then any correct solution remains correct
   after transformation.
2. If an answer passes `V(x,a)` but fails `V(T_X(x), T_A(a))`, then `V` is not invariant
   — the answer is flagged as a shortcut.
3. If transformations form a group and `V` is invariant under a generating set, then `V`
   is invariant under all composed transformations.
-/

variable {X A : Type*}

/-- Verifier invariance: `V` gives the same result before and after transformation. -/
def VerifierInvariant (V : X → A → Bool) (T_X : X → X) (T_A : A → A) : Prop :=
  ∀ x a, V x a = V (T_X x) (T_A a)

/-! ## Part 1: Invariance preserves correctness -/

/-
If `V` is invariant under `(T_X, T_A)`, then any correct solution remains correct
after the transformation is applied.
-/
theorem invariant_preserves_correct (V : X → A → Bool) (T_X : X → X) (T_A : A → A)
    (hinv : VerifierInvariant V T_X T_A) (x : X) (a : A)
    (hcorrect : V x a = true) :
    V (T_X x) (T_A a) = true := by
  rw [ ← hinv, hcorrect ]

/-! ## Part 2: Shortcut detection -/

/-
If an answer passes `V(x,a)` but fails `V(T_X(x), T_A(a))`, then `V` is not invariant
under `(T_X, T_A)`. Such an answer exploits a shortcut that breaks under transformation.
-/
theorem shortcut_violates_invariance (V : X → A → Bool) (T_X : X → X) (T_A : A → A)
    (x : X) (a : A)
    (hpass : V x a = true) (hfail : V (T_X x) (T_A a) = false) :
    ¬ VerifierInvariant V T_X T_A := by
  exact fun h => by rw [ h x a ] at hpass; aesop;

/-! ## Part 3: Group invariance from generators -/

variable {G : Type*} [Group G] [MulAction G X] [MulAction G A]

/-- The set of group elements under which `V` is invariant. -/
def invariantSet (V : X → A → Bool) : Set G :=
  {g : G | ∀ x a, V x a = V (g • x) (g • a)}

/-
The invariant set contains the identity.
-/
theorem invariantSet_one (V : X → A → Bool) : (1 : G) ∈ invariantSet (G := G) V := by
  exact fun x a => by simp +decide ;

/-
The invariant set is closed under multiplication.
-/
theorem invariantSet_mul (V : X → A → Bool) {g h : G}
    (hg : g ∈ invariantSet V) (hh : h ∈ invariantSet V) :
    g * h ∈ invariantSet (G := G) V := by
  intro x a
  simp only [mul_smul]
  rw [hh x a, hg (h • x) (h • a)]

/-
The invariant set is closed under inverses.
-/
theorem invariantSet_inv (V : X → A → Bool) {g : G}
    (hg : g ∈ invariantSet V) :
    g⁻¹ ∈ invariantSet (G := G) V := by
  intro x a;
  have := hg ( g⁻¹ • x ) ( g⁻¹ • a ) ; simp_all +decide ;

/-- The invariant set forms a subgroup. -/
def invariantSubgroup (V : X → A → Bool) : Subgroup G where
  carrier := invariantSet V
  one_mem' := invariantSet_one V
  mul_mem' := invariantSet_mul V
  inv_mem' := invariantSet_inv V

/-
If `V` is invariant under every generator in a set `S`, then `V` is invariant under
every element of the subgroup generated by `S`. That is, invariance under generators
implies invariance under all composed transformations.
-/
theorem invariant_of_generators (V : X → A → Bool) (S : Set G)
    (hS : S ⊆ invariantSet V) (g : G)
    (hg : g ∈ Subgroup.closure S) :
    g ∈ invariantSet (G := G) V := by
  refine' Subgroup.closure_induction _ _ _ _ hg;
  · exact hS;
  · exact invariantSet_one V;
  · exact fun x y hx hy hx' hy' => invariantSet_mul _ hx' hy';
  · grind +suggestions